[build-system]
requires = ["torch>=2.1.0", "numpy"]
build-backend = "setuptools.build_meta"

[dev-packages]
torch = { index = "pytorch_cu128"}

[[source]]
url = "https://download.pytorch.org/whl/cu128"
verify_ssl = true
name = "pytorch_cu128"
